var requestUrl = {
  UPLOAD_ARTICLE: '/sys/uploadArticle.json',
  UPLOAD_IMAGE: '/sys/uploadImage.json',
  GET_BLOG_LIST: '/sys/getBlogList.json',
  GET_ARTICLE_TYPE: '/sys/getArticleType.json',
  GET_RECOMMEND_USER: '/sys/getRecommendUser.json',
  GENERATE_RAND_CHECK_CODE: '/sys/generateRandCheckCode.json',
  USER_REGISTER: '/sys/register.json',
  USER_LOGIN: '/sys/login.json',
  LOGIN_REQUEST: '/sys/generateLoginRequest.json',
  GET_ARTICLE_DETAIL: '/sys/getArticleDetail.json',
  THUMBS_UP: '/sys/thumbsUp.json',
  GET_COMMENT_BY_ARTICLE_ID: '/sys/getCommentByArticleId.json',
  PUBLISH_COMMENT: '/sys/publishComment.json',
  FOLLOW: '/sys/follow.json',
  UNFOLLOW: '/sys/unfollow.json',
  QUERY_FOLLOW: '/sys/queryfollowByUserId.json',
  QUERY_USER: '/sys/queryUser.json',
  QUERY_WORD: '/sys/queryWord.json',
  PUBLISH_WORD: '/sys/publishWord.json',
  UPDATE_USER: '/sys/updateUser.json',
  UPDATE_USER_PASSWORD: '/sys/updatePassword.json',
  PACKAGE_FILE: '/sys/packageFile.json',
  CONCERN_BLOG: '/sys/getConcernBlog.json',
  QUERY_MESSAGE: '/sys/queryMessage.json',
  DELETE_MESSAGE: '/sys/deleteMessage.json'
}
module.exports = requestUrl
